#!/usr/bin/env python3
"""
discover_activation_centroids.py

Purpose
-------
Discover target-property activation representations and construct layer-specific
activation centroids for the three SWE-bench properties prepared by
prepare_dataset_and_labels.py:

    1. coupling
    2. complexity
    3. modularity

The script combines the following experimental stages:

    1. Load the prepared SWE-bench adaptation partition.
    2. Run the pretrained StarCoderBase model and extract pooled hidden
       representations from all transformer layers.
    3. Perform preliminary layer analysis to identify layers that contain the
       strongest target-property signal.
    4. Select the top-performing layers independently for each property.
    5. Optionally perform a second inference pass that stores activations only
       for the selected layers.
    6. Evaluate whether positive and negative instances form distinguishable
       activation representations using a standardized linear probe.
    7. Construct a layer-specific positive activation centroid for each target
       property.
    8. Save all activations, layer scores, probe results, selected layers, and
       centroids for subsequent activation-guided LoRA adaptation.

Expected input
--------------
outputs/prepared_swebench/prepared_dataset.pt

This input is generated by prepare_dataset_and_labels.py and must contain:

    input_ids
    attention_masks
    instance_ids
    labels
    splits

Example
-------
python discover_activation_centroids.py \
    --prepared-cache outputs/prepared_swebench/prepared_dataset.pt \
    --model-name bigcode/starcoderbase-1b \
    --output-dir outputs/activation_centroids \
    --batch-size 1 \
    --top-k-layers 4 \
    --pooling last-token \
    --dtype float16

CPU example
-----------
python discover_activation_centroids.py \
    --prepared-cache outputs/prepared_swebench/prepared_dataset.pt \
    --model-name bigcode/starcoderbase-1b \
    --output-dir outputs/activation_centroids \
    --device cpu \
    --dtype float32 \
    --batch-size 1

Outputs
-------
<output-dir>/
    all_layer_activations.pt
    selected_layer_activations.pt
    selected_layers.json
    layer_analysis.csv
    layer_analysis.json
    activation_probe_results.json
    property_centroids.pt
    centroid_statistics.json
    discovery_config.json

Methodological decisions
------------------------
* Hidden states are pooled independently for each benchmark instance.
* By default, the final non-padding prompt token is used.
* Layer selection is performed only on the adaptation partition.
* Each property is analyzed independently because labels are multi-label.
* A linear probe is used only as an analysis instrument. Its parameters are not
  used during LoRA adaptation.
* Positive centroids are computed only from positively labeled adaptation
  instances.
* The embedding output is excluded by default; transformer block outputs are
  numbered from 0 to num_hidden_layers - 1.
"""

from __future__ import annotations

import argparse
import csv
import gc
import hashlib
import json
import logging
import math
import random
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, MutableMapping, Optional, Sequence, Tuple

try:
    import numpy as np
except ImportError as exc:
    raise SystemExit("NumPy is required: pip install numpy") from exc

try:
    import torch
    import torch.nn.functional as F
    from torch.nn.utils.rnn import pad_sequence
except ImportError as exc:
    raise SystemExit(
        "PyTorch is required. Install it from https://pytorch.org/."
    ) from exc

try:
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import (
        accuracy_score,
        balanced_accuracy_score,
        f1_score,
        precision_score,
        recall_score,
        roc_auc_score,
    )
    from sklearn.model_selection import StratifiedShuffleSplit
    from sklearn.preprocessing import StandardScaler
except ImportError as exc:
    raise SystemExit(
        "scikit-learn is required: pip install scikit-learn"
    ) from exc

try:
    from transformers import AutoModelForCausalLM
except ImportError as exc:
    raise SystemExit(
        "The Hugging Face transformers package is required: "
        "pip install transformers"
    ) from exc


LOGGER = logging.getLogger("discover_activation_centroids")
PROPERTIES = ("coupling", "complexity", "modularity")


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ProbeMetrics:
    property_name: str
    layer: int
    train_size: int
    validation_size: int
    positive_train: int
    positive_validation: int
    accuracy: float
    balanced_accuracy: float
    precision: float
    recall: float
    f1: float
    roc_auc: Optional[float]
    centroid_distance: float
    cosine_separation: float
    fisher_ratio: float
    composite_score: float


@dataclass(frozen=True)
class CentroidStatistics:
    property_name: str
    layer: int
    positive_count: int
    negative_count: int
    hidden_dimension: int
    positive_mean_norm: float
    negative_mean_norm: float
    centroid_distance: float
    centroid_cosine_similarity: float
    positive_mean_distance_to_centroid: float
    negative_mean_distance_to_positive_centroid: float


# ---------------------------------------------------------------------------
# Generic utilities
# ---------------------------------------------------------------------------

def configure_logging(verbose: bool) -> None:
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
    )


def stable_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_json(path: Path, value: Any) -> None:
    with path.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, indent=2, ensure_ascii=False)


def ensure_output_dir(path: Path, overwrite: bool) -> None:
    if path.exists() and any(path.iterdir()) and not overwrite:
        raise FileExistsError(
            f"Output directory is not empty: {path}\n"
            "Use --overwrite to replace generated files."
        )
    path.mkdir(parents=True, exist_ok=True)


def resolve_device(requested: str) -> torch.device:
    requested = requested.lower()
    if requested == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")

    device = torch.device(requested)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested but is not available.")
    if device.type == "mps":
        if not getattr(torch.backends, "mps", None):
            raise RuntimeError("MPS was requested but this PyTorch build lacks MPS.")
        if not torch.backends.mps.is_available():
            raise RuntimeError("MPS was requested but is not available.")
    return device


def resolve_dtype(name: str, device: torch.device) -> torch.dtype:
    name = name.lower()
    mapping = {
        "float32": torch.float32,
        "fp32": torch.float32,
        "float16": torch.float16,
        "fp16": torch.float16,
        "bfloat16": torch.bfloat16,
        "bf16": torch.bfloat16,
    }
    if name not in mapping:
        raise ValueError(f"Unsupported dtype: {name}")

    dtype = mapping[name]
    if device.type == "cpu" and dtype == torch.float16:
        LOGGER.warning("float16 on CPU is unsupported/slow; using float32.")
        return torch.float32
    if device.type == "mps" and dtype == torch.bfloat16:
        LOGGER.warning("bfloat16 on MPS is not consistently supported; using float16.")
        return torch.float16
    return dtype


def safe_float(value: Any) -> float:
    result = float(value)
    if not math.isfinite(result):
        return 0.0
    return result


# ---------------------------------------------------------------------------
# Cache validation
# ---------------------------------------------------------------------------

def load_prepared_cache(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Prepared cache does not exist: {path}")

    LOGGER.info("Loading prepared dataset cache: %s", path)
    cache = torch.load(path, map_location="cpu", weights_only=False)

    required = {
        "instance_ids",
        "input_ids",
        "attention_masks",
        "labels",
        "splits",
    }
    missing = required - set(cache)
    if missing:
        raise KeyError(
            "Prepared cache is missing required keys: "
            + ", ".join(sorted(missing))
        )

    count = len(cache["instance_ids"])
    for key in ("input_ids", "attention_masks"):
        if len(cache[key]) != count:
            raise ValueError(
                f"Cache length mismatch: {key} has {len(cache[key])}, "
                f"expected {count}."
            )

    for property_name in PROPERTIES:
        if property_name not in cache["labels"]:
            raise KeyError(f"Missing label tensor: {property_name}")
        if len(cache["labels"][property_name]) != count:
            raise ValueError(f"Label length mismatch for {property_name}.")

    if "adaptation" not in cache["splits"]:
        raise KeyError("The cache must contain an 'adaptation' split.")

    return cache


def normalize_split_indices(value: Any) -> List[int]:
    if isinstance(value, torch.Tensor):
        return [int(item) for item in value.tolist()]
    return [int(item) for item in value]


# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------

def load_model(
    model_name: str,
    device: torch.device,
    dtype: torch.dtype,
    trust_remote_code: bool,
    low_cpu_mem_usage: bool,
) -> torch.nn.Module:
    LOGGER.info(
        "Loading model=%s device=%s dtype=%s",
        model_name,
        device,
        dtype,
    )

    kwargs: Dict[str, Any] = {
        "trust_remote_code": trust_remote_code,
        "torch_dtype": dtype,
        "low_cpu_mem_usage": low_cpu_mem_usage,
    }

    model = AutoModelForCausalLM.from_pretrained(model_name, **kwargs)
    model.eval()
    model.requires_grad_(False)
    model.to(device)

    if getattr(model.config, "use_cache", None) is not None:
        model.config.use_cache = False

    return model


def infer_transformer_layer_count(model: torch.nn.Module) -> int:
    for attr in ("num_hidden_layers", "n_layer", "num_layers"):
        value = getattr(model.config, attr, None)
        if value is not None:
            return int(value)
    raise AttributeError(
        "Could not infer the number of transformer layers from model.config."
    )


# ---------------------------------------------------------------------------
# Batching and activation extraction
# ---------------------------------------------------------------------------

def make_batch(
    input_ids_list: Sequence[torch.Tensor],
    attention_mask_list: Sequence[torch.Tensor],
    indices: Sequence[int],
    pad_token_id: int,
    device: torch.device,
) -> Tuple[torch.Tensor, torch.Tensor]:
    ids = [input_ids_list[index].to(torch.long) for index in indices]
    masks = [attention_mask_list[index].to(torch.long) for index in indices]

    padded_ids = pad_sequence(
        ids,
        batch_first=True,
        padding_value=pad_token_id,
    )
    padded_masks = pad_sequence(
        masks,
        batch_first=True,
        padding_value=0,
    )
    return padded_ids.to(device), padded_masks.to(device)


def pool_hidden_state(
    hidden_state: torch.Tensor,
    attention_mask: torch.Tensor,
    pooling: str,
) -> torch.Tensor:
    """
    Convert [batch, sequence, hidden] to [batch, hidden].

    last-token:
        Uses the final non-padding prompt token.

    mean:
        Mean over non-padding prompt tokens.

    first-token:
        Uses token position zero.
    """
    if hidden_state.ndim != 3:
        raise ValueError(
            f"Expected hidden state [B, T, H], got {tuple(hidden_state.shape)}"
        )

    if pooling == "last-token":
        lengths = attention_mask.sum(dim=1).clamp(min=1) - 1
        batch_indices = torch.arange(
            hidden_state.size(0), device=hidden_state.device
        )
        return hidden_state[batch_indices, lengths]

    if pooling == "mean":
        mask = attention_mask.unsqueeze(-1).to(hidden_state.dtype)
        numerator = (hidden_state * mask).sum(dim=1)
        denominator = mask.sum(dim=1).clamp(min=1.0)
        return numerator / denominator

    if pooling == "first-token":
        return hidden_state[:, 0, :]

    raise ValueError(f"Unsupported pooling method: {pooling}")


@torch.inference_mode()
def extract_activations(
    model: torch.nn.Module,
    cache: Mapping[str, Any],
    dataset_indices: Sequence[int],
    batch_size: int,
    pad_token_id: int,
    device: torch.device,
    pooling: str,
    selected_layers: Optional[Sequence[int]] = None,
    storage_dtype: torch.dtype = torch.float32,
) -> Dict[int, torch.Tensor]:
    """
    Extract pooled activations for all requested instances.

    Hugging Face causal language models return:
        hidden_states[0]     embedding output
        hidden_states[i + 1] transformer layer i output

    This function exposes transformer layers using zero-based numbering.
    """
    layer_count = infer_transformer_layer_count(model)
    if selected_layers is None:
        requested_layers = list(range(layer_count))
    else:
        requested_layers = sorted(set(int(layer) for layer in selected_layers))

    for layer in requested_layers:
        if layer < 0 or layer >= layer_count:
            raise IndexError(
                f"Layer {layer} is outside valid range [0, {layer_count - 1}]."
            )

    collected: Dict[int, List[torch.Tensor]] = {
        layer: [] for layer in requested_layers
    }

    total_batches = math.ceil(len(dataset_indices) / batch_size)
    for batch_number, start in enumerate(
        range(0, len(dataset_indices), batch_size), start=1
    ):
        batch_indices = dataset_indices[start : start + batch_size]
        input_ids, attention_mask = make_batch(
            cache["input_ids"],
            cache["attention_masks"],
            batch_indices,
            pad_token_id,
            device,
        )

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            output_hidden_states=True,
            use_cache=False,
            return_dict=True,
        )

        hidden_states = outputs.hidden_states
        if hidden_states is None:
            raise RuntimeError("Model did not return hidden states.")
        if len(hidden_states) != layer_count + 1:
            raise RuntimeError(
                f"Expected {layer_count + 1} hidden-state tensors, "
                f"received {len(hidden_states)}."
            )

        for layer in requested_layers:
            pooled = pool_hidden_state(
                hidden_states[layer + 1],
                attention_mask,
                pooling,
            )
            collected[layer].append(
                pooled.detach().to("cpu", dtype=storage_dtype)
            )

        del outputs, hidden_states, input_ids, attention_mask
        if device.type == "cuda":
            torch.cuda.empty_cache()
        elif device.type == "mps":
            torch.mps.empty_cache()

        if batch_number % 25 == 0 or batch_number == total_batches:
            LOGGER.info(
                "Activation extraction: batch %d/%d (%d/%d instances)",
                batch_number,
                total_batches,
                min(start + batch_size, len(dataset_indices)),
                len(dataset_indices),
            )

    result = {
        layer: torch.cat(chunks, dim=0)
        for layer, chunks in collected.items()
    }

    expected = len(dataset_indices)
    for layer, tensor in result.items():
        if tensor.size(0) != expected:
            raise RuntimeError(
                f"Layer {layer} produced {tensor.size(0)} rows; expected {expected}."
            )

    return result


# ---------------------------------------------------------------------------
# Layer analysis
# ---------------------------------------------------------------------------

def stratified_probe_indices(
    labels: np.ndarray,
    validation_fraction: float,
    seed: int,
) -> Tuple[np.ndarray, np.ndarray]:
    if labels.ndim != 1:
        raise ValueError("Labels must be one-dimensional.")

    counts = np.bincount(labels.astype(np.int64), minlength=2)
    if counts.min() < 2:
        raise ValueError(
            "Both classes require at least two instances for probe validation; "
            f"class counts={counts.tolist()}."
        )

    splitter = StratifiedShuffleSplit(
        n_splits=1,
        test_size=validation_fraction,
        random_state=seed,
    )
    dummy = np.zeros((labels.shape[0], 1), dtype=np.float32)
    train_idx, validation_idx = next(splitter.split(dummy, labels))
    return train_idx, validation_idx


def centroid_metrics(
    activations: np.ndarray,
    labels: np.ndarray,
) -> Tuple[float, float, float]:
    positive = activations[labels == 1]
    negative = activations[labels == 0]

    positive_centroid = positive.mean(axis=0)
    negative_centroid = negative.mean(axis=0)

    distance = float(np.linalg.norm(positive_centroid - negative_centroid))

    positive_norm = np.linalg.norm(positive_centroid)
    negative_norm = np.linalg.norm(negative_centroid)
    denominator = max(positive_norm * negative_norm, 1e-12)
    centroid_cosine = float(
        np.dot(positive_centroid, negative_centroid) / denominator
    )
    cosine_separation = 1.0 - centroid_cosine

    positive_variance = float(
        np.mean(np.sum((positive - positive_centroid) ** 2, axis=1))
    )
    negative_variance = float(
        np.mean(np.sum((negative - negative_centroid) ** 2, axis=1))
    )
    within_variance = max(positive_variance + negative_variance, 1e-12)
    fisher_ratio = float(distance * distance / within_variance)

    return distance, cosine_separation, fisher_ratio


def analyze_one_layer(
    property_name: str,
    layer: int,
    activations: torch.Tensor,
    labels: torch.Tensor,
    validation_fraction: float,
    seed: int,
    max_iter: int,
    class_weight: Optional[str],
) -> ProbeMetrics:
    x = activations.detach().cpu().numpy().astype(np.float64, copy=False)

    if not np.isfinite(x).all():
        raise FloatingPointError(
            f"{property_name} layer {layer} contains NaN or infinite activations."
        )
    y = labels.detach().cpu().numpy().astype(np.int64, copy=False)

    train_idx, validation_idx = stratified_probe_indices(
        y,
        validation_fraction=validation_fraction,
        seed=seed,
    )

    scaler = StandardScaler()
    x_train = scaler.fit_transform(x[train_idx])
    x_validation = scaler.transform(x[validation_idx])

    classifier = LogisticRegression(
        max_iter=max_iter,
        class_weight=class_weight,
        solver="liblinear",
        random_state=seed,
    )
    classifier.fit(x_train, y[train_idx])

    predictions = classifier.predict(x_validation)
    probabilities = classifier.predict_proba(x_validation)[:, 1]

    try:
        auc: Optional[float] = safe_float(
            roc_auc_score(y[validation_idx], probabilities)
        )
    except ValueError:
        auc = None

    distance, cosine_separation, fisher_ratio = centroid_metrics(x, y)

    balanced = safe_float(
        balanced_accuracy_score(y[validation_idx], predictions)
    )
    f1 = safe_float(
        f1_score(y[validation_idx], predictions, zero_division=0)
    )

    # The primary selection signal is validation performance. Fisher separation
    # contributes a bounded secondary term so scale differences cannot dominate.
    bounded_fisher = fisher_ratio / (1.0 + fisher_ratio)
    composite = 0.50 * balanced + 0.35 * (auc if auc is not None else 0.5)
    composite += 0.15 * bounded_fisher

    return ProbeMetrics(
        property_name=property_name,
        layer=layer,
        train_size=int(len(train_idx)),
        validation_size=int(len(validation_idx)),
        positive_train=int(y[train_idx].sum()),
        positive_validation=int(y[validation_idx].sum()),
        accuracy=safe_float(
            accuracy_score(y[validation_idx], predictions)
        ),
        balanced_accuracy=balanced,
        precision=safe_float(
            precision_score(y[validation_idx], predictions, zero_division=0)
        ),
        recall=safe_float(
            recall_score(y[validation_idx], predictions, zero_division=0)
        ),
        f1=f1,
        roc_auc=auc,
        centroid_distance=safe_float(distance),
        cosine_separation=safe_float(cosine_separation),
        fisher_ratio=safe_float(fisher_ratio),
        composite_score=safe_float(composite),
    )


def analyze_all_layers(
    activations: Mapping[int, torch.Tensor],
    labels_by_property: Mapping[str, torch.Tensor],
    validation_fraction: float,
    seed: int,
    max_iter: int,
    class_weight: Optional[str],
) -> List[ProbeMetrics]:
    results: List[ProbeMetrics] = []

    for property_offset, property_name in enumerate(PROPERTIES):
        labels = labels_by_property[property_name]
        positive_count = int(labels.sum().item())
        negative_count = int(labels.numel() - positive_count)
        LOGGER.info(
            "Analyzing property=%s positives=%d negatives=%d",
            property_name,
            positive_count,
            negative_count,
        )

        if positive_count < 2 or negative_count < 2:
            raise RuntimeError(
                f"Insufficient class support for {property_name}: "
                f"positive={positive_count}, negative={negative_count}."
            )

        for layer in sorted(activations):
            metrics = analyze_one_layer(
                property_name=property_name,
                layer=layer,
                activations=activations[layer],
                labels=labels,
                validation_fraction=validation_fraction,
                seed=seed + property_offset,
                max_iter=max_iter,
                class_weight=class_weight,
            )
            results.append(metrics)
            LOGGER.info(
                "%s layer=%d balanced_acc=%.4f auc=%s f1=%.4f score=%.4f",
                property_name,
                layer,
                metrics.balanced_accuracy,
                (
                    f"{metrics.roc_auc:.4f}"
                    if metrics.roc_auc is not None
                    else "NA"
                ),
                metrics.f1,
                metrics.composite_score,
            )

    return results


def select_layers(
    results: Sequence[ProbeMetrics],
    top_k: int,
    minimum_balanced_accuracy: float,
) -> Dict[str, List[int]]:
    selected: Dict[str, List[int]] = {}

    for property_name in PROPERTIES:
        property_results = [
            item for item in results if item.property_name == property_name
        ]
        ranked = sorted(
            property_results,
            key=lambda item: (
                item.composite_score,
                item.balanced_accuracy,
                item.roc_auc if item.roc_auc is not None else -1.0,
                item.f1,
                item.layer,
            ),
            reverse=True,
        )

        eligible = [
            item
            for item in ranked
            if item.balanced_accuracy >= minimum_balanced_accuracy
        ]

        if not eligible:
            LOGGER.warning(
                "No %s layer met minimum balanced accuracy %.3f; "
                "falling back to the highest-scoring layer.",
                property_name,
                minimum_balanced_accuracy,
            )
            eligible = ranked[:1]

        selected[property_name] = [
            item.layer for item in eligible[:top_k]
        ]

    return selected


# ---------------------------------------------------------------------------
# Centroid construction and discovery decision
# ---------------------------------------------------------------------------

def construct_centroids(
    selected_activations: Mapping[int, torch.Tensor],
    labels_by_property: Mapping[str, torch.Tensor],
    selected_layers: Mapping[str, Sequence[int]],
    minimum_probe_balanced_accuracy: float,
    probe_lookup: Mapping[Tuple[str, int], ProbeMetrics],
) -> Tuple[Dict[str, Dict[int, torch.Tensor]], List[CentroidStatistics], Dict[str, Any]]:
    centroids: Dict[str, Dict[int, torch.Tensor]] = {}
    statistics: List[CentroidStatistics] = []
    discovery: Dict[str, Any] = {}

    for property_name in PROPERTIES:
        labels = labels_by_property[property_name].to(torch.long)
        positive_mask = labels == 1
        negative_mask = labels == 0

        property_centroids: Dict[int, torch.Tensor] = {}
        qualifying_layers = 0

        for layer in selected_layers[property_name]:
            activations = selected_activations[layer].to(torch.float32)
            positive = activations[positive_mask]
            negative = activations[negative_mask]

            if positive.size(0) == 0:
                raise RuntimeError(
                    f"Cannot construct {property_name} centroid at layer {layer}: "
                    "no positive instances."
                )

            positive_centroid = positive.mean(dim=0)
            negative_centroid = negative.mean(dim=0)
            property_centroids[layer] = positive_centroid

            centroid_distance = torch.linalg.vector_norm(
                positive_centroid - negative_centroid
            )
            centroid_cosine = F.cosine_similarity(
                positive_centroid.unsqueeze(0),
                negative_centroid.unsqueeze(0),
                dim=1,
            )[0]

            positive_distance = torch.linalg.vector_norm(
                positive - positive_centroid.unsqueeze(0),
                dim=1,
            ).mean()
            negative_distance = torch.linalg.vector_norm(
                negative - positive_centroid.unsqueeze(0),
                dim=1,
            ).mean()

            statistics.append(
                CentroidStatistics(
                    property_name=property_name,
                    layer=layer,
                    positive_count=int(positive.size(0)),
                    negative_count=int(negative.size(0)),
                    hidden_dimension=int(activations.size(1)),
                    positive_mean_norm=safe_float(
                        torch.linalg.vector_norm(positive, dim=1).mean().item()
                    ),
                    negative_mean_norm=safe_float(
                        torch.linalg.vector_norm(negative, dim=1).mean().item()
                    ),
                    centroid_distance=safe_float(centroid_distance.item()),
                    centroid_cosine_similarity=safe_float(centroid_cosine.item()),
                    positive_mean_distance_to_centroid=safe_float(
                        positive_distance.item()
                    ),
                    negative_mean_distance_to_positive_centroid=safe_float(
                        negative_distance.item()
                    ),
                )
            )

            metrics = probe_lookup[(property_name, layer)]
            if metrics.balanced_accuracy >= minimum_probe_balanced_accuracy:
                qualifying_layers += 1

        centroids[property_name] = property_centroids
        discovery[property_name] = {
            "distinguishable_representation_found": qualifying_layers > 0,
            "qualifying_selected_layers": qualifying_layers,
            "selected_layer_count": len(selected_layers[property_name]),
            "criterion": (
                "At least one selected layer has probe balanced accuracy "
                f">= {minimum_probe_balanced_accuracy:.3f}."
            ),
        }

    return centroids, statistics, discovery


# ---------------------------------------------------------------------------
# Saving
# ---------------------------------------------------------------------------

def save_layer_analysis_csv(
    path: Path,
    results: Sequence[ProbeMetrics],
) -> None:
    rows = [asdict(item) for item in results]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def save_outputs(
    output_dir: Path,
    cache: Mapping[str, Any],
    adaptation_indices: Sequence[int],
    all_layer_activations: Mapping[int, torch.Tensor],
    selected_layer_activations: Mapping[int, torch.Tensor],
    selected_layers: Mapping[str, Sequence[int]],
    probe_results: Sequence[ProbeMetrics],
    centroids: Mapping[str, Mapping[int, torch.Tensor]],
    centroid_statistics: Sequence[CentroidStatistics],
    discovery: Mapping[str, Any],
    config: Mapping[str, Any],
) -> None:
    adaptation_instance_ids = [
        cache["instance_ids"][index] for index in adaptation_indices
    ]

    torch.save(
        {
            "format_version": 1,
            "instance_ids": adaptation_instance_ids,
            "source_indices": torch.tensor(
                adaptation_indices, dtype=torch.long
            ),
            "pooling": config["pooling"],
            "layer_numbering": "zero-based transformer block output",
            "activations": dict(all_layer_activations),
        },
        output_dir / "all_layer_activations.pt",
    )

    torch.save(
        {
            "format_version": 1,
            "instance_ids": adaptation_instance_ids,
            "source_indices": torch.tensor(
                adaptation_indices, dtype=torch.long
            ),
            "pooling": config["pooling"],
            "selected_layers_by_property": {
                key: list(value) for key, value in selected_layers.items()
            },
            "activations": dict(selected_layer_activations),
        },
        output_dir / "selected_layer_activations.pt",
    )

    centroid_payload = {
        "format_version": 1,
        "model_name": config["model_name"],
        "pooling": config["pooling"],
        "layer_numbering": "zero-based transformer block output",
        "selected_layers": {
            key: list(value) for key, value in selected_layers.items()
        },
        "centroids": {
            property_name: {
                int(layer): tensor.detach().cpu().to(torch.float32)
                for layer, tensor in property_centroids.items()
            }
            for property_name, property_centroids in centroids.items()
        },
        "positive_counts": {
            property_name: int(
                cache["labels"][property_name][
                    torch.tensor(adaptation_indices, dtype=torch.long)
                ].sum().item()
            )
            for property_name in PROPERTIES
        },
        "discovery": dict(discovery),
    }
    torch.save(centroid_payload, output_dir / "property_centroids.pt")

    selected_json = {
        "layer_numbering": "zero-based transformer block output",
        "selected_layers": {
            key: list(value) for key, value in selected_layers.items()
        },
        "discovery": dict(discovery),
    }
    write_json(output_dir / "selected_layers.json", selected_json)

    probe_rows = [asdict(item) for item in probe_results]
    write_json(output_dir / "layer_analysis.json", probe_rows)
    write_json(output_dir / "activation_probe_results.json", probe_rows)
    save_layer_analysis_csv(
        output_dir / "layer_analysis.csv",
        probe_results,
    )

    write_json(
        output_dir / "centroid_statistics.json",
        [asdict(item) for item in centroid_statistics],
    )
    write_json(output_dir / "discovery_config.json", dict(config))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Extract StarCoderBase activations, select target-property layers, "
            "evaluate activation separability, and build positive centroids."
        )
    )
    parser.add_argument(
        "--prepared-cache",
        type=Path,
        default=Path("outputs") / "prepared_swebench" / "prepared_dataset.pt",
    )
    parser.add_argument(
        "--model-name",
        default="bigcode/starcoderbase-1b",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("outputs") / "activation_centroids",
    )
    parser.add_argument(
        "--device",
        default="auto",
        help="auto, cpu, cuda, cuda:0, or mps",
    )
    parser.add_argument(
        "--dtype",
        default="float16",
        choices=("float32", "float16", "bfloat16"),
    )
    parser.add_argument(
        "--storage-dtype",
        default="float32",
        choices=("float32", "float16", "bfloat16"),
        help="CPU dtype used when saving pooled activations.",
    )
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument(
        "--pooling",
        choices=("last-token", "mean", "first-token"),
        default="last-token",
    )
    parser.add_argument("--top-k-layers", type=int, default=4)
    parser.add_argument(
        "--probe-validation-fraction",
        type=float,
        default=0.20,
    )
    parser.add_argument(
        "--minimum-balanced-accuracy",
        type=float,
        default=0.55,
        help=(
            "Minimum probe balanced accuracy used for layer eligibility and "
            "the activation-discovery decision."
        ),
    )
    parser.add_argument("--probe-max-iter", type=int, default=2000)
    parser.add_argument(
        "--class-weight",
        choices=("balanced", "none"),
        default="balanced",
    )
    parser.add_argument(
        "--skip-second-pass",
        action="store_true",
        help=(
            "Reuse selected tensors from the all-layer inference rather than "
            "performing the explicit second selected-layer inference pass."
        ),
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional limit on adaptation instances for a smoke test.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--trust-remote-code", action="store_true")
    parser.add_argument(
        "--disable-low-cpu-memory",
        action="store_true",
    )
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--verbose", action="store_true")
    return parser


def validate_arguments(args: argparse.Namespace) -> None:
    if args.batch_size < 1:
        raise ValueError("--batch-size must be at least 1.")
    if args.top_k_layers < 1:
        raise ValueError("--top-k-layers must be at least 1.")
    if not 0.0 < args.probe_validation_fraction < 1.0:
        raise ValueError(
            "--probe-validation-fraction must be strictly between 0 and 1."
        )
    if not 0.0 <= args.minimum_balanced_accuracy <= 1.0:
        raise ValueError(
            "--minimum-balanced-accuracy must be in [0, 1]."
        )
    if args.limit is not None and args.limit < 2:
        raise ValueError("--limit must be at least 2.")


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_argument_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose)
    validate_arguments(args)

    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    ensure_output_dir(args.output_dir, args.overwrite)

    cache = load_prepared_cache(args.prepared_cache)
    adaptation_indices = normalize_split_indices(
        cache["splits"]["adaptation"]
    )
    if args.limit is not None:
        adaptation_indices = adaptation_indices[: args.limit]

    if not adaptation_indices:
        raise RuntimeError("The adaptation partition is empty.")

    labels_by_property = {
        property_name: cache["labels"][property_name][
            torch.tensor(adaptation_indices, dtype=torch.long)
        ].to(torch.long)
        for property_name in PROPERTIES
    }

    for property_name, labels in labels_by_property.items():
        LOGGER.info(
            "Adaptation labels %s: positive=%d negative=%d",
            property_name,
            int(labels.sum().item()),
            int(labels.numel() - labels.sum().item()),
        )

    device = resolve_device(args.device)
    model_dtype = resolve_dtype(args.dtype, device)
    storage_dtype = resolve_dtype(
        args.storage_dtype,
        torch.device("cpu"),
    )

    model = load_model(
        model_name=args.model_name,
        device=device,
        dtype=model_dtype,
        trust_remote_code=args.trust_remote_code,
        low_cpu_mem_usage=not args.disable_low_cpu_memory,
    )

    layer_count = infer_transformer_layer_count(model)
    if args.top_k_layers > layer_count:
        LOGGER.warning(
            "top-k-layers=%d exceeds model layer count=%d; using %d.",
            args.top_k_layers,
            layer_count,
            layer_count,
        )
        args.top_k_layers = layer_count

    tokenizer_info = cache.get("tokenizer", {})
    pad_token_id = tokenizer_info.get("pad_token_id")
    if pad_token_id is None:
        pad_token_id = getattr(model.config, "pad_token_id", None)
    if pad_token_id is None:
        pad_token_id = getattr(model.config, "eos_token_id", None)
    if pad_token_id is None:
        raise RuntimeError(
            "Could not determine a padding token ID from the cache or model."
        )
    pad_token_id = int(pad_token_id)

    LOGGER.info(
        "First inference pass: extracting all %d transformer layers.",
        layer_count,
    )
    all_layer_activations = extract_activations(
        model=model,
        cache=cache,
        dataset_indices=adaptation_indices,
        batch_size=args.batch_size,
        pad_token_id=pad_token_id,
        device=device,
        pooling=args.pooling,
        selected_layers=None,
        storage_dtype=storage_dtype,
    )

    class_weight = (
        None if args.class_weight == "none" else args.class_weight
    )
    probe_results = analyze_all_layers(
        activations=all_layer_activations,
        labels_by_property=labels_by_property,
        validation_fraction=args.probe_validation_fraction,
        seed=args.seed,
        max_iter=args.probe_max_iter,
        class_weight=class_weight,
    )

    selected_layers = select_layers(
        results=probe_results,
        top_k=args.top_k_layers,
        minimum_balanced_accuracy=args.minimum_balanced_accuracy,
    )

    LOGGER.info("Selected layers:")
    for property_name in PROPERTIES:
        LOGGER.info(
            "  %s: %s",
            property_name,
            selected_layers[property_name],
        )

    union_selected_layers = sorted(
        {
            layer
            for property_layers in selected_layers.values()
            for layer in property_layers
        }
    )

    if args.skip_second_pass:
        LOGGER.info(
            "Second inference pass skipped; reusing selected all-layer tensors."
        )
        selected_layer_activations = {
            layer: all_layer_activations[layer]
            for layer in union_selected_layers
        }
    else:
        LOGGER.info(
            "Second inference pass: extracting selected layers %s.",
            union_selected_layers,
        )
        selected_layer_activations = extract_activations(
            model=model,
            cache=cache,
            dataset_indices=adaptation_indices,
            batch_size=args.batch_size,
            pad_token_id=pad_token_id,
            device=device,
            pooling=args.pooling,
            selected_layers=union_selected_layers,
            storage_dtype=storage_dtype,
        )

    probe_lookup = {
        (item.property_name, item.layer): item
        for item in probe_results
    }

    centroids, centroid_statistics, discovery = construct_centroids(
        selected_activations=selected_layer_activations,
        labels_by_property=labels_by_property,
        selected_layers=selected_layers,
        minimum_probe_balanced_accuracy=args.minimum_balanced_accuracy,
        probe_lookup=probe_lookup,
    )

    config = {
        "prepared_cache": str(args.prepared_cache),
        "prepared_cache_sha256": stable_hash(args.prepared_cache),
        "model_name": args.model_name,
        "device": str(device),
        "model_dtype": str(model_dtype).replace("torch.", ""),
        "storage_dtype": str(storage_dtype).replace("torch.", ""),
        "batch_size": args.batch_size,
        "pooling": args.pooling,
        "top_k_layers": args.top_k_layers,
        "probe_validation_fraction": args.probe_validation_fraction,
        "minimum_balanced_accuracy": args.minimum_balanced_accuracy,
        "probe_max_iter": args.probe_max_iter,
        "class_weight": class_weight,
        "skip_second_pass": args.skip_second_pass,
        "adaptation_instance_count": len(adaptation_indices),
        "layer_count": layer_count,
        "layer_numbering": "zero-based transformer block output",
        "seed": args.seed,
        "script_sha256": stable_hash(Path(__file__)),
    }

    save_outputs(
        output_dir=args.output_dir,
        cache=cache,
        adaptation_indices=adaptation_indices,
        all_layer_activations=all_layer_activations,
        selected_layer_activations=selected_layer_activations,
        selected_layers=selected_layers,
        probe_results=probe_results,
        centroids=centroids,
        centroid_statistics=centroid_statistics,
        discovery=discovery,
        config=config,
    )

    LOGGER.info("Activation discovery completed.")
    LOGGER.info("Results saved to %s", args.output_dir)
    for property_name in PROPERTIES:
        LOGGER.info(
            "%s: layers=%s representation_found=%s",
            property_name,
            selected_layers[property_name],
            discovery[property_name]["distinguishable_representation_found"],
        )

    del model
    gc.collect()
    if device.type == "cuda":
        torch.cuda.empty_cache()
    elif device.type == "mps":
        torch.mps.empty_cache()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
